### PR TITLE
Features/sanic integration

### PR DESCRIPTION
**Pull request by Dark04072006**

### CODE REVIEW

**Comment by Tishka17** [comment]
Pls, update docs as well

**Comment by Dark04072006** [comment]
> Pls, update docs as well

I apologize for the long wait for an answer. I was dealing with a problem with tests on version 3.12. Locally everything runs for me, version 3.12.2, but when sending a PR for version 3.12 it gives an error, I don’t know what the problem is and I didn’t find anything when searching :(

**Comment by Tishka17** [comment]
Let's try merge with current develop. Anyway, update docs and we'll continue experiments

**Comment by Dark04072006** [comment]
I found the problem. When running tests, the following trace is issued:

import pkg_resources
ModuleNotFoundError: There is no module named 'pkg_resources'. 

I solved this problem by installing the latest version of setuptools. Do you mind if I include the latest version of setuptools in the Sanic dependency file?

**Comment by Tishka17** [comment]
Sounds reasonable. Let's include it there

**Pull request merged**
